# Support vector machine (SVM)

In [48]:
#Support vector machine used for both regression and classification task
but generally they work best in classification problems 

SyntaxError: invalid syntax (1915898919.py, line 2)

In [ ]:
# the goal of svm alg is to create the best line or decision 
boundary that can segregate n dimensional space into classes so that we can 
easily put the new data point in the correct category in the future 
this best decsion boundary is known as hyperplane 

# Support Vector Regression 

In [49]:
 import pandas as pd 
    

In [50]:
df=pd.read_csv("bangalore house price prediction.csv")
df.head(4)

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   

   area_typePlot  Area  availability_Ready To Move  ...  \
0                    0                           1  ...   
1                    0                           1  ...   
2                    0                           1  ...   
3                    0                           1  ...   

   location_Kalena Agrahara  location_Horamavu Agara  location_Vidyaranyapura  \
0                         0                        0                        0   
1                         0                        0                        0   
2                         0                        0                        0   
3                         0                        0                        0   

   location_BTM 2nd Stage  location_Hebbal Kempapura  location_Hosur Road  \
0                       0                          0                    0   
1                       0                          0                    0   
2                       0                          0                    0   
3                       0                          0                    0   

   location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
0                            0                0                     0   
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   

   location_Tumkur Road  
0                     0  
1                     0  
2                     0  
3                     0  

[4 rows x 108 columns]

In [51]:
X=df.drop("price",axis=1)
y=df['price']

In [52]:
X.head(4)


bath  balcony  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0          1672.0    3     8971.291866   
1   3.0      3.0          1750.0    3     8514.285714   
2   3.0      2.0          1750.0    3     8571.428571   
3   2.0      2.0          1250.0    2     3200.000000   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   

   area_typePlot  Area  availability_Ready To Move  location_Whitefield  ...  \
0                    0                           1                    0  ...   
1                    0                           1                    0  ...   
2                    0                           1                    0  ...   
3                    0                           1                    0  ...   

   location_Kalena Agrahara  location_Horamavu Agara  location_Vidyaranyapura  \
0                         0                        0                        0   
1                         0                        0                        0   
2                         0                        0                        0   
3                         0                        0                        0   

   location_BTM 2nd Stage  location_Hebbal Kempapura  location_Hosur Road  \
0                       0                          0                    0   
1                       0                          0                    0   
2                       0                          0                    0   
3                       0                          0                    0   

   location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
0                            0                0                     0   
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   

   location_Tumkur Road  
0                     0  
1                     0  
2                     0  
3                     0  

[4 rows x 107 columns]

In [53]:
y.head(4)

0    150.0
1    149.0
2    150.0
3     40.0
Name: price, dtype: float64

In [54]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=51)


In [55]:
#feature scaling  it is imp 

In [56]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(X_train)
X_train=sc.transform(X_train)
X_test=sc.transform(X_test)

# Support Vector Regression 

In [57]:
from sklearn.svm import SVR

In [58]:
svr_rbf=SVR(kernel='rbf') #radial basis function 
svr_rbf.fit(X_train,y_train)
svr_rbf.score(X_test,y_test)


0.20638035840828173

In [59]:
svr_linear=SVR(kernel='linear') 
svr_linear.fit(X_train,y_train)
svr_linear.score(X_test,y_test)


0.7962681111981448

In [60]:
svr_poly=SVR(kernel='poly',degree=2) 
svr_poly.fit(X_train,y_train)
svr_poly.score(X_test,y_test)

0.18266215211874637

In [61]:
# predict the value of home and test

In [62]:
X_test[0]

array([ 0.71301986,  0.0112734 ,  0.30202307,  0.65677518, -0.48064341,
       -1.7385623 ,  2.11587407, -0.25430867,  0.51007548, -0.18373025,
       -0.16389438, -0.1473229 , -0.13023539, -0.12812824, -0.12598816,
       -0.12454231, -0.12953656, -0.12381344, -0.12010681, -0.11551113,
       -0.10992018, -0.10909925, -0.10660036, -0.11234866, -0.09315135,
       -0.08618799, -0.08923672, -0.09023078, -0.08721571, -0.09023078,
       -0.08721571, -0.08195215, -0.08195215, -0.07633675, -0.0751646 ,
       -0.08085949, -0.0739743 , -0.07975227, -0.07153563, -0.0751646 ,
       -0.0677166 , -0.08085949, -0.07153563, -0.07862985, -0.0751646 ,
       -0.07862985, -0.06504853, -0.0751646 , -0.06901264, -0.0751646 ,
       -0.06901264, -0.07028523, -0.07276497, -0.07028523, -0.06367332,
       -0.06226825, -0.06226825, -0.06639573, -0.06504853, -0.05935999,
       -0.06083125, -0.06639573, -0.06639573, -0.06226825, -0.06367332,
       -0.05935999, -0.06639573, -0.06367332, -0.06226825, -0.06

In [63]:
svr_linear.predict([X_test[0]])

array([86.53676526])

In [69]:
y_pred =svr_linear.predict(X_test)
y_pred   # predicted value 

array([ 86.53676526,  33.70321929, 122.48542445, ...,  26.23942664,
        64.52601454, 176.17339689])

In [70]:
y_test   # actual value 

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [71]:
from sklearn.metrics import mean_squared_error 
import numpy as np 
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)

print('mse',mse)
print('rmse',rmse)

mse 4093.5719890687483
rmse 63.981028352698026
